---
name: Data-Page
version: 2.02
author:
  - |-
    Based on code originally by Leo Lapworth, with many changes added by
    by Leon Brocard <acme@astray.com>.
abstract: help when paging through sets of results
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Chained::Fast: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Data::Page:
    file: lib/Data/Page.pm
    version: 2.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
